# Generated by Django 4.1.6 on 2023-02-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='object_type',
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='FRIENDS', max_length=50),
        ),
    ]
