# Generated by Django 4.1.6 on 2023-02-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='type',
            new_name='object_type',
        ),
    ]
