# Generated by Django 4.1.6 on 2023-02-20 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('object_type', models.CharField(max_length=50)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_host', models.URLField()),
                ('display_name', models.CharField(max_length=100)),
                ('profile_url', models.URLField(max_length=100)),
                ('author_github', models.URLField(max_length=100)),
                ('profile_image', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('comment_content', models.TextField(max_length=100)),
                ('content_type', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('comment_id', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('page', models.IntegerField()),
                ('size', models.IntegerField()),
                ('post', models.URLField(max_length=100)),
                ('comment_id', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('author', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.URLField(max_length=100)),
                ('object_type', models.CharField(max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('obj', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('post_id', models.URLField(max_length=100)),
                ('post_source', models.URLField(max_length=100)),
                ('post_origin', models.URLField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('content_type', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=100)),
                ('comment_count', models.IntegerField()),
                ('comments', models.URLField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('is_unlisted', models.BooleanField()),
                ('visibility', models.CharField(default='FRIENDS', max_length=50)),
            ],
        ),
    ]
