# Generated by Django 4.1.6 on 2023-04-05 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=30)),
                ('url_id', models.URLField(max_length=2000, unique=True)),
                ('author_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('home_host', models.URLField(max_length=2000)),
                ('display_name', models.CharField(max_length=30)),
                ('profile_url', models.URLField(max_length=2000)),
                ('author_github', models.URLField(blank=True, max_length=2000, null=True)),
                ('profile_image', models.URLField(max_length=2000)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=30)),
                ('author_actor', models.JSONField()),
                ('author_object', models.JSONField()),
                ('following_summary', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TEAM', max_length=30)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('token', models.CharField(blank=True, max_length=80, null=True)),
                ('basic', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('remote_follow_info', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=80, null=True)),
                ('url_id', models.URLField(max_length=2000, unique=True)),
                ('post_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('post_source', models.URLField(max_length=2000, null=True)),
                ('post_origin', models.URLField(max_length=2000, null=True)),
                ('description', models.TextField(blank=True, max_length=80, null=True)),
                ('content_type', models.CharField(max_length=80, null=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('comments', models.URLField(max_length=2000, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_unlisted', models.BooleanField()),
                ('visibility', models.CharField(default='PUBLIC', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='home.author', to_field='author_id')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.URLField(max_length=2000)),
                ('like_summary', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=30)),
                ('author_object', models.JSONField(null=True)),
                ('obj', models.URLField(max_length=2000)),
                ('associated_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to='home.author')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox_item', models.JSONField(blank=True, null=True)),
                ('associated_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='home.author')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_info', models.JSONField(blank=True, null=True)),
                ('follower_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_items', to='home.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=30)),
                ('url_id', models.URLField(max_length=2000, unique=True)),
                ('comment_id', models.UUIDField(unique=True)),
                ('post_id', models.UUIDField()),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('content_type', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.author', to_field='author_id')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
