# Generated by Django 4.1.6 on 2023-02-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_id',
            new_name='comments_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='content_type',
            new_name='like_summary',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='object_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='associated_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_items', to='home.author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_list', to='home.comments'),
        ),
        migrations.AddField(
            model_name='follow',
            name='author_actor',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='author_object',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='following_summary',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='followers',
            name='follower_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_items', to='home.author'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='associated_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='home.author'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbox_item',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='associated_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to='home.author'),
        ),
        migrations.AddField(
            model_name='like',
            name='author_object',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
