# Generated by Django 4.1.6 on 2023-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='state',
            field=models.CharField(default='Pending', max_length=20),
            preserve_default=False,
        ),
    ]
