# Generated by Django 4.1.6 on 2023-02-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='http://127.0.0.1:5454/authors/9de17f29c12e8f97bcbbd34cc908f1baba40658e', on_delete=django.db.models.deletion.CASCADE, to='home.author', to_field='uid'),
            preserve_default=False,
        ),
    ]
