# Generated by Django 4.1.6 on 2023-02-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
