# Generated by Django 4.1.6 on 2023-03-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_follow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='author_info',
            field=models.JSONField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
