# Generated by Django 4.1.7 on 2023-03-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_followers_author_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='author_actor',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='author_object',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='following_summary',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='followers',
            name='author_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
