# Generated by Django 4.1.6 on 2023-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_origin',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_source',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
