# Generated by Django 4.1.6 on 2023-02-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_type_author_object_type_rename_id_author_uid_and_more'),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_info', to='authors.author'),
        ),
    ]
