# Generated by Django 4.1.6 on 2023-02-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_info', to='authors.author'),
        ),
    ]
