# Generated by Django 4.1.6 on 2023-02-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_alter_followers_follower_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='author_actor',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='author_object',
            field=models.JSONField(),
        ),
    ]
